### PR TITLE
Cherry-picks for 3.6

### PR DESCRIPTION
**Pull request by GeorgesStavracas**
A set of cherry-picks that are mostly harmless, but may fix some issues.

https://phabricator.endlessm.com/T26948

### CODE REVIEW

**Comment by wjt** [comment]
I had a look at upstream's `gnome-3-32` branch and almost all of these patches are on `gnome-3-32` with the exception of “backends/x11: Do not reload keymap on new keyboard notifications”; and with the exception of the following patches, this branch contains all the patches from the `gnome-3-32` branch:

* 8b79c83ad (origin/gnome-3-32) display: Dispose Stack after Compositor and X11
* 2ce4a20c8 headless-start-test: Ignore frame counter warnings
* fb03e198e test-runner: Always wait after creating a window
* 07c9cd498 wayland/cursor-surface: Update sprite when attaching NULL
* e716f9d14 wayland/surface: Clear texture when attaching NULL

I guess that top one seems interesting. The broader point is, should we consider just merging the upstream stable branch into our downstream branch and making that the PR? It would make it much clearer that these patches are precisely those that are on the upstream stable branch except for the one that isn't – why are we cherry-picking that one, then? Do we consider it safer for our stable branch than upstream does?

**Comment by GeorgesStavracas** [comment]
Thanks for the review; dropped the extra commit not present in `gnome-3-32` and used the merge strategy here, instead of cherry-picks.

**Comment by wjt** [comment]
I think these are still cherry-picks: you are the committer in each case

**Comment by wjt** [comment]
Fine, let's merge these cherry-picks as cherry-picks.

**Pull request merged**
