### PR TITLE
3.37.92

### PR DESCRIPTION
**Pull request by GeorgesStavracas**
Dropped most of the patches for underscan compensation, they're being tracked as a [separate task](https://phabricator.endlessm.com/T30754).

### Understan Compensation patches ([T30754](https://phabricator.endlessm.com/T30754))

 * aedb79c4d monitor-config-manager: Consider underscanning when matching configs
 * 1f6bef5b0 monitor-manager-xrandr: Select cropped mode when appropriate
 * adf0e9c0d output-xrandr: add support for "crop" underscan mode
 * c4435d2bc output: Underscanning border to account for 5% of the display size
 * 68e52c45a monitor-manager: only support underscan when mode allows it
 * 1534efd46 monitor-manager: store and use underscan border xrandr values
 * be65806ae output-xrandr: Support different values for underscan atom
 * 8e4ddbd9b Record monitor connect/disconnect events.
    * This last one tangentially touches underscan and doesn't apply cleanly; needs to be updated together with the underscan series

### Upstream or die

 * 81dd492a4 compositor: add a new plugin function when unmanaged

### Picked

 * efdfdefa1 meson: Disable sysprof by default
 * 143afdbe7 meson: Disable tests by default
 * 55c2b4a12 Skip startup notifications for apps blacklisted by parental controls
 * 3fe6979d4 monitor-manager: Add a name property to the monitor modes we export
 * c49e94727 MetaSurfaceActorX11: set _GTK_WINDOW_UNREDIRECTED
 * 3a9a117a7 theme: don't center the title
 * 9daf13231 frames: Adapt to font resolution changes at runtime
 * 81852172a constraints: force saved rect of maximized-after-placement windows

### Dropped 

 * c3098045d renderer/native: Break hybrid GPU support on ARM to fix endless mini
 * 26d26fcfb Define KEY_KBDINPUTASSIST_CANCEL if needed
   * Dropping EC-100 patches ([T30317](https://phabricator.endlessm.com/T30317))
 * b78c465ec window: Add meta_window_get_minimum_size
 * ff89d721f core: Add API to allow signal listeners to constrain geometry
   * Used by Hack; we'll work around it in the extension
    
https://phabricator.endlessm.com/T30177

### CODE REVIEW

**Comment by andrunko** [comment]
> Dropped most of the patches for underscan compensation, they're being tracked as a [separate task](https://phabricator.endlessm.com/T30754).
> 
> https://phabricator.endlessm.com/T30177

Could we get a list of the downstream commits and what was done with them, similar to https://github.com/endlessm/gnome-initial-setup/pull/317? That would make it much easier to review.

**Comment by GeorgesStavracas** [comment]
Done

**Comment by andrunko** [comment]
> Dropped most of the patches for underscan compensation, they're being tracked as a [separate task](https://phabricator.endlessm.com/T30754).
> 
> ### Understan Compensation patches ([T30754](https://phabricator.endlessm.com/T30754))
> * [aedb79c](https://github.com/endlessm/mutter/commit/aedb79c4dc6b9d0f65368bb573176b0f287c15ad) monitor-config-manager: Consider underscanning when matching configs
> * [1f6bef5](https://github.com/endlessm/mutter/commit/1f6bef5b07ef1b93a6ee7efd43b47b6cc303b9fd) monitor-manager-xrandr: Select cropped mode when appropriate
> * [adf0e9c](https://github.com/endlessm/mutter/commit/adf0e9c0d947700faff060278ccb3564b4b2791b) output-xrandr: add support for "crop" underscan mode
> * [c4435d2](https://github.com/endlessm/mutter/commit/c4435d2bc8dee3a30e7a3f2d5ac8907128e127c5) output: Underscanning border to account for 5% of the display size
> * [68e52c4](https://github.com/endlessm/mutter/commit/68e52c45ac1c6183a3ef83b312581d91349ca722) monitor-manager: only support underscan when mode allows it
> * [1534efd](https://github.com/endlessm/mutter/commit/1534efd461136a191113d3a9197dab59d1ac9f3d) monitor-manager: store and use underscan border xrandr values
> * [be65806](https://github.com/endlessm/mutter/commit/be65806aebd74c2373f5f99a9572528933c481fe) output-xrandr: Support different values for underscan atom
> * [8e4ddbd](https://github.com/endlessm/mutter/commit/8e4ddbd9b4cfedf0c7c9764451bc2f819d55590d) Record monitor connect/disconnect events.
>   
>   * This last one tangentially touches underscan and doesn't apply cleanly; needs to be updated together with the underscan series
> 

Worth adding this list of commits to https://phabricator.endlessm.com/T30754.

>
> ### Upstream or die
> * [81dd492](https://github.com/endlessm/mutter/commit/81dd492a46b520aa63706407e38aa1b56dd68fec) compositor: add a new plugin function when unmanaged
> 

I guess you mean we are dropping it also - worth checking if there is anyone using it, from what I checked this was used on the commits from https://github.com/endlessm/gnome-shell/pull/405/commits, please verify if they are no longer needed/used. Looks like at least https://github.com/endlessm/gnome-shell/pull/405/commits/ba62a90c03f6055c6cc0e290e705f8b59dadd30a was on the eos3.8 branch.

> ### Picked
> * [efdfdef](https://github.com/endlessm/mutter/commit/efdfdefa173bf54e4a9d7f0dc9eabab2257ecf7a) meson: Disable sysprof by default
> * [143afdb](https://github.com/endlessm/mutter/commit/143afdbe72323b93da2906cbd6cb164155b2dba7) meson: Disable tests by default
> * [55c2b4a](https://github.com/endlessm/mutter/commit/55c2b4a12cd4df6117bbca10df0ce95015a31bb2) Skip startup notifications for apps blacklisted by parental controls
> * [3fe6979](https://github.com/endlessm/mutter/commit/3fe6979d4ca491f75b7f7ccb9d76ab069cdcdc15) monitor-manager: Add a name property to the monitor modes we export

This was recently replaced with https://github.com/endlessm/mutter/pull/113/commits/4ad95e00372ea024c13f52a2f2ea52ac46c8ce25 but looks like you are still including the old version?

> * [c49e947](https://github.com/endlessm/mutter/commit/c49e94727436141f8a3db0cf1a6b5a8edbae6490) MetaSurfaceActorX11: set _GTK_WINDOW_UNREDIRECTED
> * [3a9a117](https://github.com/endlessm/mutter/commit/3a9a117a7a31e38f69f112ab81ea81496260c070) theme: don't center the title
> * [9daf132](https://github.com/endlessm/mutter/commit/9daf132316828394dce69fd742f271be4f5c04ca) frames: Adapt to font resolution changes at runtime
> * [8185217](https://github.com/endlessm/mutter/commit/81852172ac338d9e5d9b143e5f3e7fc2df625c9e) constraints: force saved rect of maximized-after-placement windows
> 
> ### Dropped
> * [c309804](https://github.com/endlessm/mutter/commit/c3098045d202a9c8cc656edb2fe2cfedb5b33bdc) renderer/native: Break hybrid GPU support on ARM to fix endless mini
> * [26d26fc](https://github.com/endlessm/mutter/commit/26d26fcfb12976cfa8d62553c8b5ed1981e0e4f6) Define KEY_KBDINPUTASSIST_CANCEL if needed
>   
>   * Dropping EC-100 patches ([T30317](https://phabricator.endlessm.com/T30317))
> * [b78c465](https://github.com/endlessm/mutter/commit/b78c465eca8947f10bcfbc1e10b603fe3a512f7c) window: Add meta_window_get_minimum_size
> * [ff89d72](https://github.com/endlessm/mutter/commit/ff89d721fe18974a687bdd22e6296e952fbd55f2) core: Add API to allow signal listeners to constrain geometry
>   
>   * Used by Hack; we'll work around it in the extension
> 

I guess as long as you are in sync with the Hack team that is fine - saw some discussions on Slack around it.

**Comment by GeorgesStavracas** [comment]
> I guess you mean we are dropping it also - worth checking if there is anyone using it, from what I checked this was used on the commits from https://github.com/endlessm/gnome-shell/pull/405/commits, please verify if they are no longer needed/used. Looks like at least endlessm/gnome-shell@ba62a90 was on the eos3.8 branch.

What I mean is that I'll follow up with it upstream, and hold re-adding it until it's either accepted or rejected upstream. I really don't know why this has never been proposed upstream before.

> This was recently replaced with 4ad95e0 but looks like you are still including the old version?

This is just the hash, the new commit is being applied as you can see from the diff.

**Comment by andrunko** [comment]
> > I guess you mean we are dropping it also - worth checking if there is anyone using it, from what I checked this was used on the commits from https://github.com/endlessm/gnome-shell/pull/405/commits, please verify if they are no longer needed/used. Looks like at least [endlessm/gnome-shell@ba62a90](https://github.com/endlessm/gnome-shell/commit/ba62a90) was on the eos3.8 branch.
> 
> What I mean is that I'll follow up with it upstream, and hold re-adding it until it's either accepted or rejected upstream. I really don't know why this has never been proposed upstream before.
> 

Ah ok, do you think we still have time to include this before 3.38 final? May be worth keeping it downstream until then or we may just forget about it, but leaving it to you to follow-up.

> > This was recently replaced with [4ad95e0](https://github.com/endlessm/mutter/commit/4ad95e00372ea024c13f52a2f2ea52ac46c8ce25) but looks like you are still including the old version?
> 
> This is just the hash, the new commit is being applied as you can see from the diff.

Makes sense, I didnt check the full diff - have you looked at it? wayy to big hehe

**Comment by andrunko** [comment]
Good to go for me considering the comments above and the follow-ups needed.

**Comment by GeorgesStavracas** [comment]
> Ah ok, do you think we still have time to include this before 3.38 final? May be worth keeping it downstream until then or we may just forget about it, but leaving it to you to follow-up.

My rough plan is to land this next week upstream (GNOME is in hard code freeze now) and immediately roundtrip it back to our fork. If things are quick, it all will happen before our feature freeze.

**Pull request merged**
