### PR TITLE
T26224 (Debian)

### PR DESCRIPTION
**Pull request by GeorgesStavracas**
Almost exactly upstream, except:

 * Add `eos-metrics-0-dev` dependency
 * Update libmutter-4.symbols
 * Allow tests to fail

https://phabricator.endlessm.com/T26224

### CODE REVIEW

**Comment by wjt** [comment]
retest this please

**Comment by wjt** [comment]
```
The following packages have unmet dependencies:
 builddeps:/build : Depends: gnome-settings-daemon-common but it is not installable
                    Depends: gsettings-desktop-schemas-dev (>= 3.31.0) but it is not going to be installed
                    Depends: libgnome-desktop-3-dev (>= 3.27.90) but it is not going to be installed
```

I guess this can't be built until other stuff lands in master.

**Comment by wjt** [comment]
What's the rationale for allowing tests to fail?

**Comment by GeorgesStavracas** [comment]
> I guess this can't be built until other stuff lands in master.

That's correct.

> What's the rationale for allowing tests to fail?

The headless tests are known to randomly fail on a few setups. There's a Canonical guy looking into it, so I didn't pick that fight.

**Pull request merged**
