### PR TITLE
Rebase on mutter 3.36.0

### PR DESCRIPTION
**Pull request by andrunko**
Rebase on upstream 3.36.0 release.

Debian changes at https://github.com/endlessm/mutter/pull/100.

We are currently on 3.34.1 + some patches (more specifically upstream commit 943b0699968733b88381679095e87ac38a65cb1d).

Diffs:
- Old delta: git diff 943b0699968733b88381679095e87ac38a65cb1d..origin/master
- New delta: git diff 6b852e6cb30559b2ab56bb29ccc2e8f95aa89f89..T28837

Full list of patches on top of 943b0699968733b88381679095e87ac38a65cb1d and what happened to them:
- **pick** 40ee81d49 theme: use gtk_render_icon_suface to paint button icon - debian patch, refreshed with latest from debian
- **pick** 164686a18 theme: load icons as Gtk does with fallback and RTL support - debian patch, refreshed with latest from debian
- **pick** 976bf9868 meson: add back default_driver option - debian patch, refreshed with latest from debian
- **pick** c420f8e16 backends/x11: Support input-synaptics, if present. - debian patch, refreshed with latest from debian
- **pick** 579a68b3e tests: Tag 'closed-transient-no-input' tests as flaky - debian patch, refreshed with latest from debian
- **pick** f6298a941 Record monitor connect/disconnect events. - refreshed to fix small conflict
- **pick** a3c411562 constraints: force saved rect of maximized-after-placement windows
- **pick** c460c51ef frames: Adapt to font resolution changes at runtime
- **pick** 0a6b6adc0 theme: don't center the title
- **pick** a498304f8 MetaSurfaceActorX11: set _GTK_WINDOW_UNREDIRECTED - refreshed to fix small conflict
- **pick** a556c9b89 core: Add API to allow signal listeners to constrain geometry
- **pick** f62f2609c window: Add meta_window_get_minimum_size
- **pick** a770d8251 Define KEY_KBDINPUTASSIST_CANCEL if needed
- **pick** cd2670ece monitor-manager: Add a name property to the monitor modes we export
- **pick** 38ad5a3a4 output-xrandr: Support different values for underscan atom
- **pick** 12ecf72d8 monitor-manager: store and use underscan border xrandr values - refresh to fix conflict
- **drop** 32f5d6716 monitor-manager: check for underscan setting validity upfront - already upstreamed (in a slight different form) as 8665084df15190adc0d18cc77b7fcb738d3e4fa6
- **pick** a9516e135 monitor-manager: only support underscan when mode allows it - refreshed to fix conflict
- **pick** 2ec58c964 output: Underscanning border to account for 5% of the display size
- **pick** cd188f89d output-xrandr: add support for "crop" underscan mode
- **pick** a90095b21 monitor-manager-xrandr: Select cropped mode when appropriate -  - refreshed to fix conflict
- **pick** e964c7d1c monitor-config-manager: Consider underscanning when matching configs
- **pick** fd35a8af8 compositor: add a new plugin function when unmanaged
- **pick** f4cc4823d renderer/native: Break hybrid GPU support on ARM to fix endless mini - refreshed to fix small conflict
- **pick** acdc46f6b Skip startup notifications for apps blacklisted by parental controls
- **pick** e0c0a93dd meson: Disable tests by default
- **pick** 2063f3004 meson: Disable sysprof by default
- **drop** c883b0310 window-actor: Add a missing NULL-check - already upstreamed as 317ce05a27afe309b34aada2664dd6e23f0d9980
- **drop** 76febf8f9 x11: Update X11 focus before updating MetaDisplay focus - already upstreamed as 71c3f4af3196b77fb52f395238f0704e7fa4d273
- **drop** 96ce737a9 x11-display: Don't unset the X11 focused window after setting one - already upstreamed as efe5bed5b4a8706fc796dfd7dc07562a866c12ed
- **drop** 4d7549c20 x11-display: Get next serial just before using it - already upstreamed as ffa0a2484815540f34ffb696ccac193734912902
- **drop** 3f5a9f662 ClutterStage: Store clip area as a region - already upstreamed as a7f4f5b291146384af1a0b2bf84d4470d49fcbb9
- **drop** a1d53e032 ClutterStage: Use clutter_region_t for swap_region - already upstreamed as 30783949518b0b17248e245b91dd05ed6a46ad03
- **drop** 37fc36903 clutter/cogl: Ensure to paint full view if there's no buffer age support - already upstreamed as 2e9faaf67a3f57a4211bdb504a047e5b71aa8765
- **drop** fd1fdce52 clutter/cogl: Scale clip region in paint_stage() - already upstreamed as 9678fd5306acb17653ad72e0ccbbb98654eece37
- **drop** 9e166e0dd cogl: Add support for clipping regions - already upstreamed as a1116bc6c8a9460711e2d4dceb77a90250ec5de0
- **drop** 075c92bc6 clutter/cogl: Use regions for clipping if necessary - already upstreamed as 8598b654ba8e76d6c59b2de9f0bd1238b21e7834
- **drop** 2a80962c5 compositor: Use redraw clip region to cull out children - already upstreamed as e44bd2edb4e957a9a787b4d9a68e52ce4e0bbf3d
- **drop** e12a61fe1 cogl: Drop unused struct field - already upstreamed as a586f6a152e35cb05faf2f7290f45436ff0bff26
- **drop** 8e3987a0c clutter: Check updated devices with the current clip - already upstreamed as 353d7909f6abc0fa717287fc67e387c6c831f9b6
- **drop** c8ac32ff6 clutter: Drop unused API - already upstreamed as f4bf48a7d7aaf4805f6ebe434c5f5a8ec421c1cc
- **drop** 09c50baf2 clutter/stage-view: Separate offscreen and shadowfb - already upstreamed as db90c0d509f38dfd4c88b32d0cbb1ea53f399a63
- **drop** 3cab0044c cogl: Add function cogl_2d_primitives_immediate - already upstreamed as 99cc435730a38e441a1ebc7f1f26261d89351eb5
- **drop** 59019ae92 cogl: Simplify add_stencil_clip_region coordinates - already upstreamed as a48206e8276c02759b2d6caa369973897b33e7eb
- **drop** b9022b089 cogl: Upload clipping rectangles in parallel - already upstreamed as 4aab814c379326b5c434846024838c7d499e57ac
- **pick** 4bd0332c9 clutter/text: Check if attributes are equal before applying
- **drop** a67d167c3 clutter/stage: Add an API for shallow relayouts - already upstreamed as 5257c6ecc2d2c843ecc1ad5558e6a471eff5c7ee
- **drop** c2e66f435 clutter/actor: Use the new shallow relayout API - already upstreamed as 2731be6929ca8b14e3b0ddf5fd2aebce722b5664

https://phabricator.endlessm.com/T28856

### CODE REVIEW

**Comment by andrunko** [comment]
Quoting from https://phabricator.endlessm.com/T28856#807473:

Note that Jenkins is failing because it can't find pipewire-0.3 - this doesn't happen when building the debian package (as tested locally) because the packaging passes -Dremote_desktop=false which in turn relax the dependency on pipewire.
To fix this issue on Jenkins we can either make the remote_desktop option default to false or update our pipewire, please let me know what you think.

**Comment by GeorgesStavracas** [comment]
I'd be in favor of updating pipewire 0.3. I'm not a fan of keeping old dependencies up with new packages,

**Comment by andrunko** [comment]
After discussions on Slack we decided to disable mutter remote desktop support until pipewire-0.3 is in the distro/debian.

Branch updated accordingly.

**Comment by andrunko** [comment]
retest this please

**Comment by andrunko** [comment]
Force pushed branch after rebasing on top of latest upstream/master (which is a few commits on top of 3.36.0 and includes the fix for the arm build issue we found while testing - https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1123).

No conflicts during this rebase.

**Pull request merged**
